### ISSUE TITLE
build analyze/export phase cost too much time

### ISSUE THREAD

**Issue by zhoufenqin** [buildpacks/lifecycle#1007]
### Summary

When I create a cnbimage, I found the `analyze` and `export` step will cost a long time. For example
```
 initContainerStatuses:
  - containerID: xxx
    state:
      terminated:
        containerID: xxx
        exitCode: 0
        finishedAt: "2023-02-08T11:00:52Z"
        reason: Completed
        startedAt: "2023-02-08T11:00:21Z"
  - containerID: xxx
    name: analyze
    state:
      terminated:
        containerID: xxx
        exitCode: 0
        finishedAt: "2023-02-08T11:03:59Z"
        reason: Completed
        startedAt: "2023-02-08T11:01:58Z"
  - containerID: xxx
    name: detect
    state:
      terminated:
        containerID: xxx
        exitCode: 0
        finishedAt: "2023-02-08T11:04:06Z"
        reason: Completed
        startedAt: "2023-02-08T11:03:59Z"
  - containerID: xxx
    name: restore
    state:
      terminated:
        containerID: xxx
        exitCode: 0
        finishedAt: "2023-02-08T11:04:07Z"
        reason: Completed
        startedAt: "2023-02-08T11:04:07Z"
  - containerID: xxx
    name: build
    state:
      terminated:
        containerID: xxx
        exitCode: 0
        finishedAt: "2023-02-08T11:04:17Z"
        reason: Completed
        startedAt: "2023-02-08T11:04:08Z"
  - containerID: xxx
    name: export
    state:
      terminated:
        containerID: xxx
        exitCode: 0
        finishedAt: "2023-02-08T11:06:08Z"
        reason: Completed
        startedAt: "2023-02-08T11:04:17Z"
```

it will cost about 2 mins to finish `analyze` and `export`.

The build is the first build, so there is no previous image existing, the logs show:
```
> k logs -f {podname} -c analyze
Previous image with name "xxx" not found
```

What factors will influence the `analyze` and `export` phases? why for the first build, it will cost so long time to analyze? whether vent environment affect these two phases? I'm not very clear about the analyze phase logic.

BTW, I test in my k8s cluster, the builder image already exists in the node, so pull the builder image for `analyze` container is not the main reason, it may costs in detail analyze step. 

---

##### Current behavior
analyze and export phases cost too much time

##### Expected
speed up these two phases

---

##### lifecycle version
0.14.3
##### platform version(s)
kpack 0.7.2

**Comment by natalieparellano** [comment]
@zhoufenqin thanks for reporting this issue. I agree that the amount of time spent in the analyze step is quite long. We have seen performance issues with the analyzer before, but on older lifecycle versions and only when exporting to a docker daemon. So it would be interesting to see what is going on here.

At a high level, the analyzer reads metadata from the previous image and the run image, saving the data to analyzed.toml. It also copies the SBOM layer from the previous image (if it exists) to the local layers directory (this is the step where we saw performance issues in the past).

Worth noting, I recently fixed an [incorrect log message](https://github.com/buildpacks/lifecycle/pull/1004) in the analyzer, so it's possible that the previous image does exist, and the log message you are seeing is a failure to find the run image.

If possible it would be helpful to see the contents of analyzed.toml after the analyzer has finished and the contents of the `<layers>/sbom` directory. Additionally if you can provide `-log-level debug` when invoking the lifecycle, that might give us helpful information.

**Comment by zhoufenqin** [comment]
Hi @natalieparellano, I add `-log-level debug` to enable debug logs, the logs show below. **But before printing the first line, it almost already cost 2 mins**, which part cost time to analyze?
```
> k logs -f {podname} -c analyze
Analyzing image "xx.azurecr.io/xxx@sha256:xxx"
Restoring data for SBOM from previous image
Retrieving previous image SBOM layer for "sha256:xxx"
Analyzing image "mcr.microsoft.com/azurespringapps/paketobuildpacks/run@sha256:xx"
```

**Comment by natalieparellano** [comment]
@zhoufenqin that is unfortunate - sadly I can't think of what could be taking so long before `Analyzing image "xx.azurecr.io/xxx@sha256:xxx"` is printed. At a high level, the analyzer:
* [Reads command line inputs](https://github.com/buildpacks/lifecycle/blob/4659c442e41128bfa7d4782a25487caf575eaafc/cmd/lifecycle/analyzer.go#L28)
* [Constructs a registry keychain](https://github.com/buildpacks/lifecycle/blob/4659c442e41128bfa7d4782a25487caf575eaafc/cmd/lifecycle/analyzer.go#L86)
* [Ensures ownership of directories](https://github.com/buildpacks/lifecycle/blob/4659c442e41128bfa7d4782a25487caf575eaafc/cmd/lifecycle/analyzer.go#L97) - potentially, traversing these directories could take awhile if they are very large
* [Drops privileges](https://github.com/buildpacks/lifecycle/blob/4659c442e41128bfa7d4782a25487caf575eaafc/cmd/lifecycle/analyzer.go#L100)
* [Ensures registry access to referenced images](https://github.com/buildpacks/lifecycle/blob/4659c442e41128bfa7d4782a25487caf575eaafc/analyzer.go#L71)
* [Parses the previous image reference](https://github.com/buildpacks/lifecycle/blob/4659c442e41128bfa7d4782a25487caf575eaafc/analyzer.go#L185) `xx.azurecr.io/xxx@sha256:xxx` which is where you see the log line

Unfortunately, we don't have debug statements at these earlier steps to help us :( We can plan to add them in the next lifecycle, but in the meantime, you might try building your own lifecycle with log lines added. If that's not feasible, there are a couple other things we could try - for example, providing invalid inputs (`-flag foo` or `-run-image <inaccessible run image>`) that would cause the analyzer to fail at specific points in the process. LMK how you'd like to proceed and I could help guide you further.

**Comment by matejvasek** [comment]
>BTW, I test in my k8s cluster, the builder image already exists in the node, so pull the builder image for analyze container is not the main reason, it may costs in detail analyze step.

I have no experience with `kpack` whatsoever, just with Tekton builds.
With Tekton, the build task cannot access k8s node image storage. It has to pull everything all the time.
Coudn't it be the same case for `kpack` @natalieparellano ?

**Comment by matejvasek** [comment]
Is it possible to use custom lifecycle image with `kpack`? If so I created `quay.io/boson/lifecycle:pprof-amd64`, it should spit out `*.prof` to launch cache directory (probably some volume in k8s). From that we can see more.

**Comment by matejvasek** [comment]
@zhoufenqin I created `quay.io/mvasek/builder:base` and `quay.io/mvasek/lifecycle:0.16.0-amd64`. It should dump profiling info to stdout. Please try it out.

**Comment by zhoufenqin** [comment]
Hi @matejvasek I try `quay.io/mvasek/builder:base` and the debug log shows below, **the action is the same as above, before printing the first line, it already costs 1-2 mins**
```
    name: analyze
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: xx
        exitCode: 0
        finishedAt: "2023-02-15T07:45:44Z"
        reason: Completed
        startedAt: "2023-02-15T07:43:42Z"
```

```
Starting profiler...
Analyzing image "xx.azurecr.io/build-service-result-image-778dbdc04d4945869f7f586fd02e9935-default-test1-default@sha256:xx"
Restoring data for SBOM from previous image
Retrieving previous image SBOM layer for "sha256:xx"
Analyzing image "mcr.microsoft.com/azurespringapps/paketobuildpacks/run-bionic-base@sha256:xx"
BLOCKING PROFILE BEGIN
 xxx
CPU PROFILE BEGIN
xxx
CPU PROFILE END
```

Does the data sensitive? I can't decode it with base64, I paste the whole log in [pivotaltracker](https://www.pivotaltracker.com/story/show/184458618/comments/235539860), can you see it?
