### ISSUE TITLE
Use of insecure registry for exporter

### ISSUE THREAD

**Issue by FredPraca** [buildpacks/lifecycle#1425]
### Summary
I currently try to run _cnb_ command in a _Gitlab_ runner.
As I'm in a closed network with access to a _Gitlab_ server and a Nexus proxy proxying _OCI_ images as well as Maven artifacts and others, I have to configure a lot of things to make it work. 
The problem is that both servers use a trust CA unknown to containers (whenever it's a CA from Gandi but that's another story).

For this task, I used 

```
    - export CNB_PLATFORM_API=0.14
    - export CNB_INSECURE_REGISTRIES=gitlab.example.com:5005,nexus.example.com:5000
    - export CNB_RUN_IMAGE=nexus.example.com:5000/paketobuildpacks/run-jammy-tiny:latest
    - /cnb/lifecycle/creator -app . -platform $PLATFORM_PATH $CI_REGISTRY_IMAGE:latest
```

The result is always the same

```
===> EXPORTING
Reusing layers from image 'gitlab.example.com:5005/dev/my-project@sha256:2f7406504e3a3078c0147844939d72ef80fa7bac30a00bebf39eab7ecf055070'
ERROR: failed to access run image: connect to repo store "nexus.example.com:5000/paketobuildpacks/run-jammy-tiny:latest": Get "https://nexus.example.com:5000/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

I also tried to force the insecure registry with the following but got the same result

```
    - export CNB_PLATFORM_API=0.14
    - export CNB_INSECURE_REGISTRIES=gitlab.example.com:5005,nexus.example.com:5000
    - export CNB_RUN_IMAGE=nexus.example.com:5000/paketobuildpacks/run-jammy-tiny:latest
    - /cnb/lifecycle/creator -app . -platform $PLATFORM_PATH --insecure-registry nexus.example.com:5000 $CI_REGISTRY_IMAGE:latest
```

---

##### Steps

1. Close the access to Docker registry
2. Setup a proxy to it with a custom certificate

##### Current behavior
As described, I get a TLS certificate verification error.

##### Expected behavior
_CNB_INSECURE_REGISTRIES_ should be used to avoid checking registry certificate

---

##### lifecycle version
Lifecycle version is the one from the _paketobuildpacks/builder-jammy-tiny image_ : 0.20.3+dd23dd7d

##### platform version(s)
As used in the configuration, I use 0.14 architecture version.

**Comment by natalieparellano** [comment]
Ah, I see the issue - we're passing the insecure options through when we instantiate the app image [here](https://github.com/buildpacks/lifecycle/blob/0690d133cabea9a747ca439ba027824de6fc527b/cmd/lifecycle/exporter.go#L349) but not when we instantiate the run image [here](https://github.com/buildpacks/lifecycle/blob/0690d133cabea9a747ca439ba027824de6fc527b/cmd/lifecycle/exporter.go#L355). I can probably make a quick fix for this

**Comment by FredPraca** [comment]
Cool, it's a bug. First of all,  I thought I became crazy :smile:

**Comment by FredPraca** [comment]
Wowww, super fast :+1:

**Comment by FredPraca** [comment]
Sorry for the delay.
I tested it using latest _builder-jammy-tiny_ image and it works like a charm.

Thanks again

**Comment by cmoulliard** [comment]
I did a test using Platform 0.13 but lifecycle is reporting the error `tls: failed to verify certificate: x509: certificate signed by unknown authority` even if we set the parameter `-insecure-registry=gitea.cnoe.localtest.me:8443`

```
ERROR: failed to initialize analyzer: validating registry write access: failed to ensure registry read/write access to [gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello:](http://gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello:) creating push check transport for [gitea.cnoe.localtest.me:8443](http://gitea.cnoe.localtest.me:8443/) failed: Get "https://gitea.cnoe.localtest.me:8443/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority; GET http://gitea.cnoe.localtest.me:8443/v2/: unexpected status code 400 Bad Request: <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
```
using as arguments
```
computeResources: {}env:  - name: CNB_PLATFORM_API
    value: '0.13'
  - name: CNB_EXPERIMENTAL_MODE
    value: 'true'
  - name: HOME
    value: /tekton/home
args:  - '-log-level=info'
  - '-layers=/layers'
  - '-run-image=paketobuildpacks/run-ubi8-base:0.0.111'
  - '-cache-image='
  - '-uid=1002'
  - '-gid=1000'
  - '-insecure-registry=gitea.cnoe.localtest.me:8443'
  - gitea.cnoe.localtest.me:8443/giteaadmin/quarkus-hello
command:  - /cnb/lifecycle/analyzer
image: paketobuildpacks/builder-ubi8-base:0.0.201
imagePullPolicy: Always
name: analyze
volumeMounts:  
- mountPath: /layers
    name: layers-dir
```
Do you know why ?
