### ISSUE TITLE
Remove top-level version in build plan

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/lifecycle#330]
RFC Text: https://github.com/buildpacks/rfcs/blob/main/text/0043-increase-build-plan-flexibility.md
RFC PR: https://github.com/buildpacks/rfcs/pull/82
Spec PR: https://github.com/buildpacks/spec/pull/97
Spec Issue: https://github.com/buildpacks/spec/issues/91

### Behavior
Given a buildpack declaring buildpack API `0.3+` The `version` key should be removed from the build plan and buildpack plan.

IF an `0.3` buildpack sets `requires.version` THEN fail.

#### Passing `0.2` Requirements to `0.3` Providers
**Given** A `version` requirement from an `0.2` buildpack
```toml
[[requires]]
name = "<dependency name>"
version = "<dependency version>"

[requires.metadata]
some-key = "some-val"
```
**If** This requirement is met by an `0.3` buildpack
**Then** `version` should be converted to `metadata.version` in the buildpack plan, leaving the original  top-level `version`
```toml
[[entries]]
name = "<dependency name>"
version = "<dependency version>"

[entries.metadata]
some-key = "some-val"
version = "<dependency version>"
```

#### Passing `0.3` requirements to `0.2` Providers
**Given** A `version` metadata requirement from an `0.3` buildpack
```toml
[[requires]]
name = "<dependency name>"

[requires.metadata]
version = "<dependency version>"
some-key = "some-val"
```
**If** This requirement is met by an `0.2` buildpack
**Then** `metadata.version` should be converted to `version` in the buildpack plan
```toml
[[entries]]
name = "<dependency name>"
version = "<dependency version>"

[entries.metadata]
some-key = "some-val"
```
#### Error cases
**If** an `0.3` buildpack sets `requires.version`
**Then** the lifecycle should warn

**If** an `0.2` buildpack sets `requires.version` and `requires.metadata.version`
**And** these values are not equal to each other.
**Then** then the lifecycle should fail

### Issue History
**Updated** to account for https://github.com/buildpacks/spec/pull/110
