### ISSUE TITLE
Is there a way to run an ad-hoc python command inside the runimage utilizing the proper runtime?

### ISSUE THREAD

**Issue by dmitry-mightydevops** [buildpacks/lifecycle#523]
For example, below I am unable to launch django's manage.py as dependencies are not available (yet launcher 

I understand I can do **PYTHONPATH**:
```
export PYTHONPATH=/layers/google.python.pip/pip/lib/python3.8/site-packages/
```
but it seems that I am doing something incorrectly or maybe my expectation is wrong and that is done automatically by the launcher.

* run image: gcr.io/buildpacks/gcp/run:v1
* build image: gcr.io/buildpacks/builder:v1 

I'm building the image inside tekton's pipeline.

```
🐳  [] pga-backend-debug-pod / # find / -iname python
find: '/etc/ssl/private': Permission denied
find: '/proc/tty/driver': Permission denied
find: '/root': Permission denied
/usr/share/gcc-8/python
/usr/share/doc/libkml-dev/examples/python
/usr/include/boost/mpi/python
/usr/include/boost/parameter/aux_/python
/usr/include/boost/python
find: '/var/cache/apt/archives/partial': Permission denied
find: '/var/cache/ldconfig': Permission denied
/var/lib/python
/layers/google.python.runtime/python
/layers/google.python.runtime/python/bin/python
/layers/google.python.pip/pip/lib/python3.8/site-packages/faker/providers/python
/layers/google.python.pip/pip/lib/python3.8/site-packages/notebook/static/components/codemirror/mode/python
/layers/google.python.pip/pip/lib/python3.8/site-packages/parso/python

🐳  [] pga-backend-debug-pod / # which python3
/usr/bin/python3

🐳  [] pga-backend-debug-pod / # cd /workspace/app/

🐳  [] pga-backend-debug-pod app # python3 manage.py --help
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

🐳  [] pga-backend-debug-pod app # find /layers/google.python.pip/pip/lib/python3.8/site-packages/ -iname django
/layers/google.python.pip/pip/lib/python3.8/site-packages/django
/layers/google.python.pip/pip/lib/python3.8/site-packages/django/forms/jinja2/django
/layers/google.python.pip/pip/lib/python3.8/site-packages/django/forms/templates/django
/layers/google.python.pip/pip/lib/python3.8/site-packages/notebook/static/components/codemirror/mode/django
```

so If I create the pod this way:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pga-backend-debug-pod
spec:
  containers:
  - name: backend-app
    image: xxx.dkr.ecr.us-west-2.amazonaws.com/backend:latest
    imagePullPolicy: Always
    #command: ["/cnb/lifecycle/launcher", "web"]
    command:
      - /bin/bash
      - -c
      - |
        sleep 3000
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: workdir
      mountPath: /workspace/app/config/settings
  restartPolicy: Never
  # These containers are run during pod initialization
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
```

and then login inside I am unable to run the python commands properly. However if I set command to `["/cnb/lifecycle/launcher", "web"]` then everything works.

**Comment by natalieparellano** [comment]
@dmitry-mightydevops you are correct that the launcher is responsible for preparing the environment. Do you mind confirming which `CNB_PLATFORM_API` you are using?

**Comment by dmitry-mightydevops** [comment]
Hi Natalie,

I found what the issue was, I was incorrectly passing arguments to docker, everything works right now. However I have another question:

I'm using CNB_PLATFORM_API 0.3 - is it the latest version? How to track what is the latest version #?

```
stepTemplate:
    env:
      - name: CNB_PLATFORM_API
        value: "0.3"
```

thanks,
Dmitry
